### ISSUE TITLE
Resize  window problem

### ISSUE THREAD

**Issue by AntonyM55** [servetgulnaroglu/ytb_matrix_js#1]
When I resize the windows, there are some blanks, 
I added  code to update the width and Height, 
but it not work, 

let update = () => {
  
  cw = window.innerWidth;
  ch = window.innerHeight;
 ...
}

**Comment by tarantino07** [comment]
I solved the issue. Can you pull the last commit? Your code didn't work because it is not enough to update cw and ch. You also need to update the variables that are calculated with cw and ch. Such as maxColumns = cw / fontSize
